Resources:
  myRepo2824D906:
    Type: AWS::CodeCommit::Repository
    Properties:
      Code:
        S3:
          Bucket:
            Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
          Key: 5bfe6828d0dfd065706c0edb44dc72a311411bc8ef6849e41cd4f46ad50a83f8.zip
      RepositoryName: myRepo
    Metadata:
      aws:cdk:path: DevToolsStack/myRepo/Resource
  myProjectBuilderRole9F00805C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: DevToolsStack/myProjectBuilder/Role/Resource
  myProjectBuilderRoleDefaultPolicy46376E59:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: codecommit:GitPull
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - myRepo2824D906
                - Arn
          - Action:
              - s3:Abort*
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
              - s3:PutObject
              - s3:PutObjectLegalHold
              - s3:PutObjectRetention
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - :s3:::ankurnigam-lambda-s3-demo-bucket
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - :s3:::ankurnigam-lambda-s3-demo-bucket/*
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: myProjectBuilder232B37C5
                    - :*
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: myProjectBuilder232B37C5
          - Action:
              - codebuild:BatchPutCodeCoverages
              - codebuild:BatchPutTestCases
              - codebuild:CreateReport
              - codebuild:CreateReportGroup
              - codebuild:UpdateReport
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":codebuild:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :report-group/
                  - Ref: myProjectBuilder232B37C5
                  - -*
        Version: "2012-10-17"
      PolicyName: myProjectBuilderRoleDefaultPolicy46376E59
      Roles:
        - Ref: myProjectBuilderRole9F00805C
    Metadata:
      aws:cdk:path: DevToolsStack/myProjectBuilder/Role/DefaultPolicy/Resource
  myProjectBuilder232B37C5:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Location: ankurnigam-lambda-s3-demo-bucket
        NamespaceType: BUILD_ID
        OverrideArtifactName: true
        Packaging: ZIP
        Type: S3
      Cache:
        Type: NO_CACHE
      EncryptionKey: alias/aws/s3
      Environment:
        ComputeType: BUILD_LAMBDA_1GB
        Image: aws/codebuild/amazonlinux-aarch64-lambda-standard:nodejs20
        PrivilegedMode: false
        Type: ARM_LAMBDA_CONTAINER
      ServiceRole:
        Fn::GetAtt:
          - myProjectBuilderRole9F00805C
          - Arn
      Source:
        BuildSpec: lambda/buildspec.yml
        Location:
          Fn::GetAtt:
            - myRepo2824D906
            - CloneUrlHttp
        Type: CODECOMMIT
      SourceVersion: refs/heads/main
    Metadata:
      aws:cdk:path: DevToolsStack/myProjectBuilder/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02Nyw6CQAxFv8X9UB+4cKvuXBn8AFOGaiowNbRIzGT+3QAmujqnyb23G1hvd7Ba4KCZr+qs4RLixdDXDge9Rs2vqEqmsB/hNIdD72uyAyo5LxV5aVs2iAU9Rdmke7vjLfyuNKXKnpsK4rmTB3kbE19NjrGFWEhDU2/kWRr208xsKbnp+8XwzuHuClLpOz8X/vwooWJjCcmd8IXLzRpWkC8eypx1fTBuCYqZH6KPV834AAAA
    Metadata:
      aws:cdk:path: DevToolsStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - il-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

